name: deploy-epac-definitions-v3

on:
  push:
    branches: [ main, master ]
    paths:
      - "Definitions/policyDefinitions/**/*.json"
      - ".github/workflows/deploy-epac-definitions-v3.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug – show workflow + files
        shell: bash
        run: |
          echo "REF=$GITHUB_REF  SHA=$GITHUB_SHA  WORKFLOW=$GITHUB_WORKFLOW"
          echo "--- WORKFLOW FILE CONTENT ---"
          sed -n '1,200p' .github/workflows/deploy-epac-definitions-v3.yml || true
          echo "----- policy files -----"
          find Definitions/policyDefinitions -type f -name '*.json' -print || true

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate & publish policy definitions (subscription scope)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $api = '2021-06-01'
          $sub = '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          $files = Get-ChildItem -Path 'Definitions/policyDefinitions' -Recurse -Filter '*.json'
          if (-not $files) { throw 'No JSONs found under Definitions/policyDefinitions'; }

          foreach ($f in $files) {
            $jsonText = Get-Content -Raw -Path $f.FullName
            try { $json = $jsonText | ConvertFrom-Json } catch { throw "Invalid JSON in $($f.FullName): $($_.Exception.Message)" }

            $name = if ($json.name -and $json.name.Trim()) { $json.name.Trim() } else { [IO.Path]::GetFileNameWithoutExtension($f.Name) }
            if (-not $name) { throw "Policy name could not be determined for file $($f.FullName)" }

            # CONSTRUIR URL CON ?api-version=  (OJO: escapar ? con acento grave `)
            $uri = "https://management.azure.com/subscriptions/$sub/providers/Microsoft.Authorization/policyDefinitions/$name`?api-version=$api"
            Write-Host "PUT $uri (file=$($f.Name) name=$name)"

            az rest --method put --url $uri --headers "Content-Type=application/json" --body "@$($f.FullName)"
          }

      - name: Verify definitions published
        shell: pwsh
        run: |
          $files = Get-ChildItem 'Definitions/policyDefinitions' -Recurse -Filter '*.json'
          foreach ($f in $files) {
            $json = (Get-Content -Raw $f.FullName | ConvertFrom-Json)
            $name = if ($json.name -and $json.name.Trim()) { $json.name.Trim() } else { [IO.Path]::GetFileNameWithoutExtension($f.Name) }
            $dn = az policy definition show --name $name --query "properties.displayName" -o tsv 2>$null
            Write-Host "Published: $name → $dn"
          }
